service: server

useDotenv: true

provider:
    name: aws
    runtime: nodejs18.x
    stage: dev
    region: us-east-1
    deploymentMethod: direct
    
    environment:
        NODE_ENV: ${env:NODE_ENV}

functions:
    app:
        handler: dist/index.handler
        events:
            - http: ANY /
            - http: 'ANY /{proxy+}'

plugins:
    - serverless-offline

custom:
    serverless-offline:
        httpPort: 5000